backend: # 連携するリポジトリの設定
  name: git-gateway
  branch: master

publish_mode: editorial_workflow # ここで下書き機能を有効化

media_folder: "contents/images" # 画像ファイル等を保存するフォルダを指定

collections: # ここで個別に collection とそれが持つフィールドを設定
  - name: "blog" # collection の識別子
    label: "Blog" # 管理画面で表示されるラベル
    folder: "contents/blog" # collection のファイルが格納されるフォルダ
    create: true # 新規投稿を許可するかどうか
    slug: "{{year}}-{{month}}-{{day}}" # ここで指定した命名規則でファイルを生成
    fields:
      - {
          label: "タイトル (必須)", # 投稿画面で表示されるラベル
          name: "title", # フィールドの識別子
          widget: "string", # フィールドの形式を設定
        }
      - {
          label: "投稿日時 (必須)",
          name: "date",
          widget: "string",
          hint: "e.g. 2021年1月1日",
        }
      - {
          label: "本文 (必須)",
          name: "body",
          widget: "markdown",
          hint: "本文はリッチテキスト形式でお願いします。画像がある場合も本文に含めて下さい。",
        }
      - {
          label: "テンプレートタイプ",
          name: "type",
          widget: "hidden",
          default: "blog",
        }
